name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: "Scorecard analysis"
    # Запускается только для публичного репозитория.
    if: ${{ !github.event.repository.private }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Артефакт SARIF
        uses: actions/upload-artifact@v7
        with:
          name: scorecard-sarif
          path: results.sarif
          retention-days: 5

      - name: Загрузка в code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
